spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/cars?createDatabaseIfNotExist=true&autoReconnect=true
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true